source "https://rubygems.org"
ruby RUBY_VERSION

# Using up to date Jekyll
gem "jekyll", "3.4.3"

# This is the default theme for new Jekyll sites.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# Plugins
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end

